### ISSUE TITLE
changes to pre-request scripts at the collection level do not get saved

### ISSUE THREAD

**Issue by braveheart55** [MrCodingB/Postman-Collection-Explorer-VS-Code#15]
**Describe the bug**
Changes to pre-request scripts at the collection level do not get saved.

This is my first attempt at saving anything, so there could be more to this than described in the reproducer

**To Reproduce**

1. Open a collection 
2. Right click on the collection and select "pre-request script"
3. Make an edit to the pre-request script"
4. Save by <cmd|ctrl>s or File=>Save
5. Verify the change was saved
  a.  git status (if under git source code control) should show the collection was changed
  a.  open the collection file vscode explorer and check the change in the editor
  c.  in the vscode explorer check for 'U' next to the collection (designates updated)

**Expected behavior**
The collection file should contain the update after save

**Screenshots**
<img width="1483" alt="Screen Shot 2022-08-26 at 12 47 41 PM" src="https://user-images.githubusercontent.com/87720697/186953498-2fd7d251-703d-4765-8eda-62bff38e51aa.png">

**Environment (please complete the following information):**
 - OS macOs Big Sur 11.6.6 (20G624)
 - VS Code Version 1.70.1
 - Postman Collection Explorer v0.2.2

**Comment by MrCodingB** [comment]
This is fixed in v0.3.1
